name: Metrics Status
on: 
  workflow_dispatch:
  schedule:
    - cron: 45 11 * * *

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate SVG
        uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: Magic-Xin
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Hong_Kong
          plugin_isocalendar: true
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_lines: yes
          plugin_traffic: yes
